- name: configuring_yum_using_ansible
  gather_facts: No
  become: true
  become_method: sudo
  hosts: web1
  tasks:
  - name: creating_directory
    file:
      path: "/dvd"
      state: directory
      mode: "0755"
    register: dvd

  - name: folder created successfully
    debug:
      var: dvd

  - name: mounting_dvd
    mount:
      path: /dvd
      src: /dev/cdrom
      fstype: iso9660
      opts: ro,noauto
      state: mounted
    register: mount_dvd

  - name: dvd_mounted successfully
    debug:
      var: mount_dvd.changed

  - name: yum_repo_BaseOS
    yum_repository:
      name: BaseOS
      description: Local_baseos
      file: dvd1
      baseurl: file:///dvd/BaseOS
      gpgcheck: no

  - name: yum_repo_AppStream
    yum_repository:
      name: AppStream
      description: Local_appstream
      file: dvd2
      baseurl: file:///dvd/AppStream
      gpgcheck: no

  - name: yum_clean_caches
    shell: "yum clean all"
    register: clean_all

  - name: clean_caches
    debug:
      var: clean_all.stdout_lines

  - name: yum_repository
    shell: "yum repolist"
    register: yum_repo

  - name: repo
    debug:
      var: yum_repo.stdout_lines


-  name: task_10
   gather_facts: No
   hosts: web2
   tasks:
   - name: Remove docker if installed from CentOS repo
     yum:
       name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
       state: removed
     register: remove

   - name: unwanted softwares removed successfully
     debug:
       var: remove.results

   - name: Install yum utils
     yum:
       name: yum-utils
       state: latest
  
   - name: Adding docker repo
     yum_repository:
      name: download.docker.com_linux_centos_7_x86_64_stable_
      description: download.docker.com_linux_centos_7_x86_64_stable_
      file: download.docker.com_linux_centos_7_x86_64_stable_
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      enabled: yes

   - name: Install Docker
     shell: "yum install --nobest docker-ce -y"
     register: docker

   - name: docker installed successfully
     debug:
       var: docker

   - name: Start Docker service
     service:
       name: docker
       state: started
       enabled: yes
     become: yes
     register: d_service

   - name: docker service started successfully
     debug:
       var: d_service

   - name: docker-py
     shell: "pip3 install docker"

   - name: pull an image
     docker_image:
       name: httpd
       source: pull

   - name: creating a httpd container
     docker_container:
       name: myhttpd
       image: httpd
       state: started
       published_ports:
       - "6379:80"
       volumes:
       - "/var/www/html/:/usr/local/apache2/htdocs/:ro"
     register: container

   - name: container launched successfully
     debug:
       var: container       
